name: NPM Publishing Process

on:
  push:
    branches:
      - main

env:
  NAME: 'tagmaster'
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  SCOPE: '@imraan-hendricks'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Prepare Package.json
        run: |
          jq 'del(.name) | .name = "${{ env.SCOPE  }}/${{ env.NAME  }}"' package.json > tmp.json && mv tmp.json package.json
          jq 'del(.publishConfig)' package.json > tmp.json && mv tmp.json package.json

      - name: Installing Dependencies
        run: npm ci

      - name: Performing Unit Testing
        run: npm run test:jest-ci

      - name: Creating Production Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
